apiVersion: argoproj.io/v1alpha1
kind: ApplicationSet
metadata:
  name: dev-nbg-apps
  namespace: argocd
spec:
  goTemplate: true
  generators:
    - list:
        elements:
          - app: headlamp
            env: dev
          - app: metrics-server
            env: dev
          - app: reloader
            env: dev
          - app: renovate
            env: dev
          - app: kubescape
            env: dev
          - app: local-path-provisioner
            env: dev
          # - app: ollama
          #   env: dev
          - app: grafana
            env: dev
          - app: loki
            env: dev
          - app: promtail
            env: dev
          - app: victoriametrics
            env: dev
            releaseName: vm
          - app: tempo
            env: dev
          - app: otel-collector
            env: dev
  template:
    metadata:
      name: "{{ .app }}"
      namespace: argocd
    spec:
      project: default
      source:
        repoURL: http://gitea-http.gitea.svc.cluster.local:3000/admin/app-of-apps.git
        targetRevision: main
        path: "apps/{{ .app }}"
        helm:
          releaseName: "{{ if .releaseName }}{{ .releaseName }}{{ else }}{{ .app }}{{ end }}"
          valueFiles:
            - values.yaml
            - "values-{{ .env }}.yaml"
      destination:
        server: https://kubernetes.default.svc
        namespace: "{{ .app }}"
      syncPolicy:
        automated:
          prune: true
          selfHeal: true
        syncOptions:
          - CreateNamespace=true
          - ServerSideApply=true
