# apps/victoriametrics/Chart.yaml
apiVersion: v2
name: victoriametrics
description: VictoriaMetrics k8s stack
type: application
version: 0.1.0
dependencies:
  - name: victoria-metrics-k8s-stack
    version: "*"
    repository: https://victoriametrics.github.io/helm-charts/
