apiVersion: v2
name: loki
description: Grafana Loki (umbrella chart)
type: application
version: 0.1.0
dependencies:
  - name: loki
    version: "*"   # renovate: datasource=helm registryUrl=https://grafana.github.io/helm-charts
    repository: https://grafana.github.io/helm-charts
