# Minimal OpenTelemetry Collector to receive OTLP and forward to Tempo
opentelemetry-collector:
  image:
    repository: "otel/opentelemetry-collector-k8s"
  mode: deployment
  config:
    receivers:
      otlp:
        protocols:
          grpc: {}
          http: {}
      zipkin: {}
    processors:
      batch: {}
    exporters:
      otlp:
        endpoint: tempo.tempo.svc.cluster.local:4317
        tls:
          insecure: true
    service:
      pipelines:
        traces:
          receivers: [otlp, zipkin]
          processors: [batch]
          exporters: [otlp]
