apiVersion: v2
name: local-path-provisioner
description: Rancher Local Path Provisioner (umbrella chart)
type: application
version: 0.1.0
dependencies:
  - name: local-path-provisioner
    version: "*"   # renovate: datasource=helm registryUrl=https://rancher.github.io/local-path-provisioner/
    repository: https://rancher.github.io/local-path-provisioner/
