apiVersion: v2
name: grafana
description: Grafana (umbrella chart)
type: application
version: 0.1.0
dependencies:
  - name: grafana
    version: "*"   # renovate: datasource=helm registryUrl=https://grafana.github.io/helm-charts
    repository: https://grafana.github.io/helm-charts
